// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOB_3oNGiwJ-Lb5ELqjmFxBaAnh4cTGro',
    appId: '1:672138384804:web:ce55ef52b43c4a24d2dd31',
    messagingSenderId: '672138384804',
    projectId: 'car-fix-e0bb2',
    authDomain: 'car-fix-e0bb2.firebaseapp.com',
    storageBucket: 'car-fix-e0bb2.appspot.com',
    measurementId: 'G-2R9YQQK60C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQdm1d4MrWX6MXiV6NMfaKbLXkSFN1rUE',
    appId: '1:672138384804:android:624a432caccd35b3d2dd31',
    messagingSenderId: '672138384804',
    projectId: 'car-fix-e0bb2',
    storageBucket: 'car-fix-e0bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZaFH9Lb1KnyOpmddgzt_ZtZwKjrxLIQ',
    appId: '1:672138384804:ios:f8b7524001684667d2dd31',
    messagingSenderId: '672138384804',
    projectId: 'car-fix-e0bb2',
    storageBucket: 'car-fix-e0bb2.appspot.com',
    iosClientId: '672138384804-qng2nnlo4u0givsk2kb7irf44a221qh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZaFH9Lb1KnyOpmddgzt_ZtZwKjrxLIQ',
    appId: '1:672138384804:ios:f8b7524001684667d2dd31',
    messagingSenderId: '672138384804',
    projectId: 'car-fix-e0bb2',
    storageBucket: 'car-fix-e0bb2.appspot.com',
    iosClientId: '672138384804-qng2nnlo4u0givsk2kb7irf44a221qh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp1',
  );
}
